### ISSUE TITLE
amdgpu-opencl-switcher is missing from copr

### ISSUE THREAD

**Issue by vwbusguy** [CosmicFusion/fedora-amdgpu-pro#14]
I've been trying to get this going on Fedora 37, rebuilding the packages in copr manually from src.rpm.  The [docs mention](https://github.com/CosmicFusion/fedora-amdgpu-pro#how-to-use-the-opencl-drivers) an amdgpu-opencl-switcher package that doesn't seem to exist in the linked COPR repo and I don't see if in previous builds.  I have rebuilt and installed the vulkan and opengl switchers, but neither provide the cl_pro command.

**Comment by Manu3l0us** [comment]
@vwbusguy I have the same issue, have you found a solution in the meantime?

**Comment by CosmicFusion** [comment]
The repos are out dated sadly you can find the switcher in https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara/

**Comment by Manu3l0us** [comment]
Thank you very much, this helped

**Comment by vwbusguy** [comment]
Nice!  Would you happen to have an ETA of when F37 might also be supported there?

**Comment by CosmicFusion** [comment]
Nope IDK
________________________________
