### ISSUE TITLE
Library path is incorrent for gl_pro

### ISSUE THREAD

**Issue by vwbusguy** [CosmicFusion/fedora-amdgpu-pro#15]
The gl_pro command sets the wrong path for includes causing it to instafail.

```
$ gl_pro glxgears
libGL error: MESA-LOADER: failed to open radeonsi: /opt/amdgpu-pro/OpenGL/lib32/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /opt/amdgpu-pro/OpenGL/lib64/dri:/opt/amdgpu-pro/OpenGL/lib32/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /opt/amdgpu-pro/OpenGL/lib32/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /opt/amdgpu-pro/OpenGL/lib64/dri:/opt/amdgpu-pro/OpenGL/lib32/dri, suffix _dri)
libGL error: failed to load driver: swrast
Error: glXCreateContext failed
```

gl_pro() exports:

`export LD_LIBRARY_PATH="/opt/amdgpu-pro/OpenGL/lib64:/opt/amdgpu-pro/OpenGL/lib32:${LD_LIBRARY_PATH}" LIBGL_DRIVERS_PATH="/opt/amdgpu-pro/OpenGL/lib64/dri:/opt/amdgpu-pro/OpenGL/lib32/dri"`

The actual path from the installed RPMs had "OpenGL" in lowercase:

`/opt/amdgpu-pro/opengl/lib64/`

Changing that export line to this makes it work properly on my system (Fedora 37, x86_64):

`export LD_LIBRARY_PATH="/opt/amdgpu-pro/opengl/lib64:/opt/amdgpu-pro/opengl/lib32:${LD_LIBRARY_PATH}" LIBGL_DRIVERS_PATH="/opt/amdgpu-pro/opengl/lib64/dri:/opt/amdgpu-pro/opengl/lib32/dri"`

**Comment by CosmicFusion** [comment]
fixing tomorrow

**Comment by CosmicFusion** [comment]
ahh lol i forget to update, so the wrapper isn't actually borken, u just need the latest version from the nobara copr
