### ISSUE TITLE
nothing provides libdrm-pro (Fedora 37)

### ISSUE THREAD

**Issue by Daniel-Salvado** [CosmicFusion/fedora-amdgpu-pro#20]
I'm assuming the reason for this problem is that I'm using Fedora 37?

Or am I missing a repository?

**Comment by CosmicFusion** [comment]
You need to use the package-builder script to make this package too

**Comment by Daniel-Salvado** [comment]
Yes that was it. I don't know how I didn't think about that. Thank you.
