### ISSUE TITLE
Clarification on support for HIP/ROCm/Blender>3.0

### ISSUE THREAD

**Issue by jjlrjjlr** [CosmicFusion/fedora-amdgpu-pro#22]
As the title says, there doesn't seem to be any clarification on whether this would help with installing HIP/ROCm packages, or whether this can help with getting Blender 3.x versions to recognize AMD GPUs. Some clarification on this would be appreciated as currently only OpenCL is mentioned in regards to Blender.

**Comment by GloriousEggroll** [comment]
nothing in this repo provides support for blender HIP support. blender HIP support solely relies on rocm packages, -not- amd official drivers.
