### ISSUE TITLE
Why is libdrm-pro a required package for amdvlk?

### ISSUE THREAD

**Issue by bruno-fs** [CosmicFusion/fedora-amdgpu-pro#25]
Specifically refereeing to the following line
https://github.com/CosmicFusion/fedora-amdgpu-pro/blob/main/x86_64/amdvlk/amdvlk.spec#L54

I in particular was interested  to use amdvlk for one of the 0.001% of games where it performs better than radv. Locally I changed the spec marking `libdrm-pro` as required and not only the build was successful I could play games with it using `vk_amdvlk`.
Shouldn't we change libdrm-pro to be a recommended package instead of required or am I missing something?

Thanks for the awesome work  o/

**Comment by CosmicFusion** [comment]
It is safer to load the drm library the amdvlk was actually compiled against

99% of the time, it doesn't matter since since drm rarely gets breaking changes... but it happend once (21.50)

and since it does no harm, only additional safety we use drmpro with amdvlk
